[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[identity]
  provider = "gotrue"

[functions]
  node_bundler = "esbuild"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200