[build]
  publish = "public"
  functions = "netlify/functions"

[identity]
  provider = "gotrue"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/c/:calendarId"
  to = "/calendar.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200