[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/c/:calendarId"
  to = "/calendar.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200